### ISSUE TITLE
rather a question than an issue: advantage of running eonbot in a docker environment?

### ISSUE THREAD

**Issue by jpfl** [jakkie/eonbot-docker#1]
Hello,
what is the advantage of running eonbot in a dock environment?
i have purchased the bot and run it since some days on my windows 10 PC.
What would be different running it with docker?
is this maybe for safety or maybe running more stable?

Cheers

**Comment by jakkie** [comment]
Docker comes really in handy when you run it in a vps or cloud environment like on a cheap digital ocean linux server where you only have to install docker and run the command I mentioned and it will download and run eonbot. If you have to install eonbot on a linux server then its quite a few commands to run every time so docker helps with that to make it painless. I also don't run the eonbot bot on my local pc because sometimes the internet can be of a issue for me and eonbot can miss some trades and leave you with bags. So its better for me to run eonbot on a cloud server 24hours without interruptions. What also nice is for whatever reason eonbot crashes, docker will just restart eonbot. For me its been more stable that way. When a new version of eonbot comes out and I update the Dockerfile its then also easy just to stop and pull the new version and start it again. Saves time to maintain it. Hope that helps.

**Comment by jpfl** [comment]
that's amazing. I will try that. I had the bot stopping a few times on my windows cmd line though my internet is stable. when you update the bot to the latest version does it automatically take your configs, subconfigs and database from it's last run on the old version?
do you run the gui locally or on the cloud server/vps for changing settings?

**Comment by jpfl** [comment]
which minimum requirement in terms of CPU power  and memory would you suggest for eonbot? would any of the standard droplets at digital ocean do? and which version of linux?

**Comment by jakkie** [comment]
the wiki says Minimum VPS System Requirements: Single core processor and 512mb of ram. So you can choose the lowest ubuntu 17.10 droplet.
You can setup docker to reuse your config after upgrade to new eonbot version and i suggest to see on my last section on to use docker-compose. What is great on the new eonbot version 1.4.0 is that once your docker is up and running and you change your configs from the desktop version of eonbot and connect to your docker, you can save your new settings to it without restarting eonbot. Maybe I should update the readme on how to do that.
